# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 13:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cont',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Jkj jkj', null=True),
        ),
    ]
