# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0b\u5355\u65f6\u95f4')),
                ('sure_tiem', models.DateTimeField(verbose_name='\u786e\u8ba4\u6536\u8d27\u65f6\u95f4')),
                ('send_time', models.DateTimeField(verbose_name='\u53d1\u8d27\u65f6\u95f4')),
                ('send_company', models.CharField(max_length=20, verbose_name='\u7269\u6d41\u516c\u53f8')),
                ('send_code', models.CharField(max_length=20, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
    ]
