# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('admin', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u4eba\u5458')),
                ('reason', models.CharField(max_length=200, verbose_name='\u4fee\u6539\u7406\u7531')),
                ('end_point', models.CharField(max_length=20, verbose_name='\u6700\u540e\u79ef\u5206')),
                ('var_point', models.CharField(max_length=20, verbose_name='\u589e\u51cf\u79ef\u5206')),
            ],
            options={
                'verbose_name': '\u79ef\u5206\u8868',
                'verbose_name_plural': '\u79ef\u5206\u8868',
            },
        ),
    ]
